@startuml

skinparam packageStyle rectangle

actor User <<human>>

:OLED: <<Display>> as display
:Warning: <<LED Light>> as warning
:Alert: <<Speaker>> as alert

(See Temperature in Celsius) as (temp)
(See Systolic Pressure in mmHg) as (sysPressure)
(See Diastolic Pressue in mmHg) as (diasPressure)
(See Battery Life remaining in %) as (battery)
(See Pulse Rate in BPM) as (pulseRate)

(Get notified if Systolic Pressure goes outside\
 \nsafe range: 40 mmHg ± 10mmHg) as sysPressureRange

(Get notified if Diastolic Pressure goes outside\
 \nsafe range: 80 mmHg ± 10mmHg) as diasPressureRange

(Get notified if Temperature goes outside\
 \nsafe range: 36.1C to 37.8C) as temperatureRange

(Get notified if Pulse Rate goes outside\
 \nsafe range: 60 BPM to 100 BPM) as pulseRateRange

(Get notified if Battery Life  goes below\
 \nsafe range: >20% left remaining) as batteryLifeRange
left to right direction
User--> (temp)
User--> (sysPressure)
User--> (diasPressure)
User--> (battery)
User--> (pulseRate)

(temp)-->display
(sysPressure)-->display
(diasPressure)-->display
(battery)-->display
(pulseRate)-->display

User-up-> (temperatureRange)
User-up-> (sysPressureRange)
User-up-> (diasPressureRange)
User-up-> (batteryLifeRange)
User-up-> (pulseRateRange)

(temperatureRange)-up-> warning
(sysPressureRange)-up-> warning
(diasPressureRange)-up-> warning
(batteryLifeRange)-up-> warning
(pulseRateRange)-up-> warning

(temperatureRange)-up-> alert
(sysPressureRange)-up-> alert
(diasPressureRange)-up-> alert
(batteryLifeRange)-up-> alert
(pulseRateRange)-up-> alert

@enduml
